### ISSUE TITLE
Ocean Dycore

### ISSUE THREAD

**Issue by cmbengue** [CliMA/ClimaOcean.jl#10]
# The Climate Modeling Alliance
### Purpose

This issue details and guides the development of the Ocean Dynamical Core.

#### Requirements

- [ ] Computes 30 simulation years per day

#### Constraints

- [ ] Uses shared memory on GPUs

#### Quality Criteria

- [ ] Conserves some conserved quantity

#### Approach

We will implement a known solution found in the literature (details found in the input section)

### Cost/Benefits/Risks

To Be Determined (TBD)

### Personnel and Resources

TBD

### Composition of the Solution

- Julia Source Code
- Unit, Regression, and Integration Tests
- API Documentation
- End user documentation

### Inputs

TBD

### Key Results and Deliverables

- [ ] Run global ocean simulations at 1/36 & 100 levels with CATKE
- [ ] Demonstrate scaling on n GPUs
- [ ] Run a global cube sphere simulation at 1 degree resolution

### Task Breakdown And Tentative Due Date

```[tasklist]
### Gordon Bell
- [ ] Split-explicit on. multi GPU
- [ ] Apply to Google Cloud for 16 GPUs
```

```[tasklist]
### Run a global cube sphere simulation run at 1 degree resolution
- [ ] Implement cube sphere
```

***
- Approved by: Raf
- Approval date:

### CC
@rafferarri @cmbengue
